# .github/workflows/deploy.yml

name: Deploy Firy Streak Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5' # Use sua versão
          channel: 'stable'
          cache: true

      # --- NOVOS PASSOS COMEÇAM AQUI ---

      # 4A. Instala a CLI do FlutterFire
      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli

      # 4B. Gera o firebase_options.dart
      # Este comando vai gerar o arquivo usando as credenciais do Firebase.
      # O --project=firy-streak diz para qual projeto gerar.
      # O --non-interactive impede que ele faça perguntas.
      - name: Generate Firebase Options
        run: flutterfire configure --project=firy-streak --yes --platforms=web
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRY_STREAK }}

      # --- FIM DOS NOVOS PASSOS ---

      # 5. Instala as dependências do Flutter
      # Movido para depois da geração do firebase_options para garantir que tudo esteja no lugar.
      - name: Install Dependencies
        run: flutter pub get

      # 6. Build do aplicativo Web
      - name: Build Web App
        run: flutter build web --release # Adicionado --release para um build otimizado

      # 7. Deploy no Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRY_STREAK }}'
          projectId: 'firy-streak'
          channelId: live